version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    image: liquibase/liquibase:latest
    command: >-
      --url=${DATABASE_URL} --changeLogFile=/liquibase/changelog/master.xml update
    volumes:
      - ./migrations:/liquibase/changelog
    depends_on:
      - db

  auth:
    build: ./auth-service
    env_file: .env
    restart: always
    depends_on:
      - db

  backend:
    build: ./backend
    env_file: .env
    restart: always
    depends_on:
      - auth
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - auth

volumes:
  pgdata: